services:
  people-frontend:
    container_name: people-frontend
    image: nexus:8081/docker-releases/people_frontend_development:1.0.28
    networks:
      - development
    hostname: people-frontend
    ports:
      - 5100:5173
    environment:
      VITE_PEOPLE_BACKEND_HOST: http://localhost:4000
  people-backend:
    container_name: people-backend
    image: nexus:8081/docker-releases/people_backend_development:1.0.14
    networks:
      - development
    hostname: people-backend
    ports:
      - 4000:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: people_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - development
    shm_size: 128mb
    hostname: postgres
    environment:
      POSTGRES_DB: people_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
networks:
  development:
    driver: bridge

