services:
  people-frontend:
    container_name: people-frontend
    image: nexus:8081/docker-releases/people_frontend:1.2.4
    networks:
      - internal
    hostname: people-frontend
    ports:
      - 5100:5173
    environment:
      VITE_PEOPLE_BACKEND_HOST: http://people-backend.localhost
      VITE_TIMESHEET_FRONTEND_URL: http://timesheet.localhost
      VITE_INVOICES_FRONTEND_URL: http://invoices.localhost
      VITE_PEOPLE_HOST: people-frontend
    labels:
      - "traefik.http.routers.people-frontend.rule=Host(`people.localhost`)"
      - "traefik.http.services.people-frontend.loadbalancer.server.port=5173"
  timesheet-frontend:
    container_name: timesheet-frontend
    image: nexus:8081/docker-releases/timesheet_frontend:1.2.2
    networks:
      - internal
    hostname: timesheet-frontend
    ports:
      - 5101:5174
    environment:
      VITE_INVOICES_BACKEND_HOST: http://invoices-backend.localhost
      VITE_PEOPLE_BACKEND_HOST: http://people-backend.localhost
      VITE_TIMESHEET_BACKEND_HOST: http://timesheet-backend.localhost
      VITE_PEOPLE_FRONTEND_URL: http://people.localhost
      VITE_INVOICES_FRONTEND_URL: http://invoices.localhost
      VITE_TIMESHEET_HOST: timesheet-frontend
    labels:
      - "traefik.http.routers.timesheet-frontend.rule=Host(`timesheet.localhost`)"
      - "traefik.http.services.timesheet-frontend.loadbalancer.server.port=5174"
  invoices-frontend:
    container_name: invoices-frontend
    image: nexus:8081/docker-releases/invoices_frontend:1.0.1
    networks:
      - internal
    hostname: invoices-frontend
    ports:
      - 5102:5175
    environment:
      VITE_INVOICES_BACKEND_HOST: http://invoices-backend.localhost
      VITE_PEOPLE_BACKEND_HOST: http://people-backend.localhost
      VITE_TIMESHEET_BACKEND_HOST: http://timesheet-backend.localhost
      VITE_PEOPLE_FRONTEND_URL: http://people.localhost
      VITE_TIMESHEET_FRONTEND_URL: http://timesheet.localhost
      VITE_INVOICES_HOST: invoices-frontend
    labels:
      - "traefik.http.routers.invoices-frontend.rule=Host(`invoices.localhost`)"
      - "traefik.http.services.invoices-frontend.loadbalancer.server.port=5175"
  people-backend:
    container_name: people-backend
    image: nexus:8081/docker-releases/people_backend:1.2.1
    networks:
      - internal
    hostname: people-backend
    ports:
      - 4000:8080
    environment:
      POSTGRES_HOST: postgres-people
      POSTGRES_PORT: 5432
      POSTGRES_DB: people_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      postgres-people:
        condition: service_healthy
    labels:
      - "traefik.http.routers.people-backend.rule=Host(`people-backend.localhost`)"
      - "traefik.http.services.people-backend.loadbalancer.server.port=8080"
  timesheet-backend:
    container_name: timesheet-backend
    image: nexus:8081/docker-releases/timesheet_backend:1.2.1
    networks:
      - internal
    hostname: timesheet-backend
    ports:
      - 4001:8081
    environment:
      POSTGRES_HOST: postgres-timesheet
      POSTGRES_PORT: 5432
      POSTGRES_DB: timesheet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      INVOICES_BACKEND_HOST: http://invoices-backend:8082
      PEOPLE_BACKEND_HOST: http://people-backend:8080
    depends_on:
      postgres-timesheet:
        condition: service_healthy
    labels:
      - "traefik.http.routers.timesheet-backend.rule=Host(`timesheet-backend.localhost`)"
      - "traefik.http.services.timesheet-backend.loadbalancer.server.port=8081"
  invoices-backend:
    container_name: invoices-backend
    image: nexus:8081/docker-releases/invoices_backend:1.0.0
    networks:
      - internal
    hostname: invoices-backend
    ports:
      - 4002:8082
    environment:
      POSTGRES_HOST: postgres-invoices
      POSTGRES_PORT: 5432
      POSTGRES_DB: invoices_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      TIMESHEET_BACKEND_HOST: http://timesheet-backend:8081
      PEOPLE_BACKEND_HOST: http://people-backend:8080
    depends_on:
      postgres-invoices:
        condition: service_healthy
    labels:
      - "traefik.http.routers.invoices-backend.rule=Host(`invoices-backend.localhost`)"
      - "traefik.http.services.invoices-backend.loadbalancer.server.port=8082"
  postgres-people:
    container_name: postgres-people
    image: postgres:latest
    networks:
      - internal
    shm_size: 128mb
    hostname: postgres-people
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-people:/var/lib/postgresql/
    environment:
      POSTGRES_DB: people_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-timesheet:
    container_name: postgres-timesheet
    image: postgres:latest
    networks:
      - internal
    shm_size: 128mb
    hostname: postgres-timesheet
    ports:
      - 5433:5432
    volumes:
      - ./postgresql-timesheet:/var/lib/postgresql/
    environment:
      POSTGRES_DB: timesheet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-invoices:
    container_name: postgres-invoices
    image: postgres:latest
    networks:
      - internal
    shm_size: 128mb
    hostname: postgres-invoices
    ports:
      - 5434:5432
    volumes:
      - ./postgresql-invoices:/var/lib/postgresql/
    environment:
      POSTGRES_DB: invoices_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  people-frontend-dev:
    container_name: people-frontend-dev
    image: nexus:8081/docker-releases/people_frontend_development:1.2.5
    networks:
      - internal
    hostname: people-frontend-dev
    ports:
      - 5300:5173
    environment:
      VITE_PEOPLE_BACKEND_HOST: http://people-backend.dev.localhost
      VITE_TIMESHEET_FRONTEND_URL: http://timesheet.dev.localhost
      VITE_INVOICES_FRONTEND_URL: http://invoices.dev.localhost
      VITE_PEOPLE_HOST: people-frontend-dev
    labels:
      - "traefik.http.routers.people-frontend-dev.rule=Host(`people.dev.localhost`)"
      - "traefik.http.services.people-frontend-dev.loadbalancer.server.port=5173"
  timesheet-frontend-dev:
    container_name: timesheet-frontend-dev
    image: nexus:8081/docker-releases/timesheet_frontend_development:1.2.3
    networks:
      - internal
    hostname: timesheet-frontend-dev
    ports:
      - 5301:5174
    environment:
      VITE_INVOICES_BACKEND_HOST: http://invoices-backend.dev.localhost
      VITE_PEOPLE_BACKEND_HOST: http://people-backend.dev.localhost
      VITE_TIMESHEET_BACKEND_HOST: http://timesheet-backend.dev.localhost
      VITE_PEOPLE_FRONTEND_URL: http://people.dev.localhost
      VITE_INVOICES_FRONTEND_URL: http://invoices.dev.localhost
      VITE_TIMESHEET_HOST: timesheet-frontend-dev
    labels:
      - "traefik.http.routers.timesheet-frontend-dev.rule=Host(`timesheet.dev.localhost`)"
      - "traefik.http.services.timesheet-frontend-dev.loadbalancer.server.port=5174"
  invoices-frontend-dev:
    container_name: invoices-frontend-dev
    image: nexus:8081/docker-releases/invoices_frontend_development:1.0.6
    networks:
      - internal
    hostname: invoices-frontend-dev
    ports:
      - 5302:5175
    environment:
      VITE_INVOICES_BACKEND_HOST: http://invoices-backend.dev.localhost
      VITE_PEOPLE_BACKEND_HOST: http://people-backend.dev.localhost
      VITE_TIMESHEET_BACKEND_HOST: http://timesheet-backend.dev.localhost
      VITE_PEOPLE_FRONTEND_URL: http://people.dev.localhost
      VITE_TIMESHEET_FRONTEND_URL: http://timesheet.dev.localhost
      VITE_INVOICES_HOST: invoices-frontend-dev
    labels:
      - "traefik.http.routers.invoices-frontend-dev.rule=Host(`invoices.dev.localhost`)"
      - "traefik.http.services.invoices-frontend-dev.loadbalancer.server.port=5175"
  people-backend-dev:
    container_name: people-backend-dev
    image: nexus:8081/docker-releases/people_backend_development:1.2.2
    networks:
      - internal
    hostname: people-backend-dev
    ports:
      - 4200:8080
    environment:
      POSTGRES_HOST: postgres-people-dev
      POSTGRES_PORT: 5432
      POSTGRES_DB: people_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      postgres-people-dev:
        condition: service_healthy
    labels:
      - "traefik.http.routers.people-backend-dev.rule=Host(`people-backend.dev.localhost`)"
      - "traefik.http.services.people-backend-dev.loadbalancer.server.port=8080"
  timesheet-backend-dev:
    container_name: timesheet-backend-dev
    image: nexus:8081/docker-releases/timesheet_backend_development:1.2.2
    networks:
      - internal
    hostname: timesheet-backend-dev
    ports:
      - 4201:8081
    environment:
      POSTGRES_HOST: postgres-timesheet-dev
      POSTGRES_PORT: 5432
      POSTGRES_DB: timesheet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      INVOICES_BACKEND_HOST: http://invoices-backend-dev:8082
      PEOPLE_BACKEND_HOST: http://people-backend-dev:8080
    depends_on:
      postgres-timesheet-dev:
        condition: service_healthy
    labels:
      - "traefik.http.routers.timesheet-backend-dev.rule=Host(`timesheet-backend.dev.localhost`)"
      - "traefik.http.services.timesheet-backend-dev.loadbalancer.server.port=8081"
  invoices-backend-dev:
    container_name: invoices-backend-dev
    image: nexus:8081/docker-releases/invoices_backend_development:1.0.9
    networks:
      - internal
    hostname: invoices-backend-dev
    ports:
      - 4202:8082
    volumes:
      - ./invoices-dev:/var/invoices
    environment:
      POSTGRES_HOST: postgres-invoices-dev
      POSTGRES_PORT: 5432
      POSTGRES_DB: invoices_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      TIMESHEET_BACKEND_HOST: http://timesheet-backend-dev:8081
      PEOPLE_BACKEND_HOST: http://people-backend-dev:8080
      INVOICES_DIR: /var/invoices
    depends_on:
      postgres-invoices-dev:
        condition: service_healthy
    labels:
      - "traefik.http.routers.invoices-backend-dev.rule=Host(`invoices-backend.dev.localhost`)"
      - "traefik.http.services.invoices-backend-dev.loadbalancer.server.port=8082"
  postgres-people-dev:
    container_name: postgres-people-dev
    image: postgres:latest
    networks:
      - internal
    shm_size: 128mb
    hostname: postgres-people-dev
    ports:
      - 5632:5432
    volumes:
      - ./postgresql-people-dev:/var/lib/postgresql/
    environment:
      POSTGRES_DB: people_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-timesheet-dev:
    container_name: postgres-timesheet-dev
    image: postgres:latest
    networks:
      - internal
    shm_size: 128mb
    hostname: postgres-timesheet-dev
    ports:
      - 5633:5432
    volumes:
      - ./postgresql-timesheet-dev:/var/lib/postgresql/
    environment:
      POSTGRES_DB: timesheet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-invoices-dev:
    container_name: postgres-invoices-dev
    image: postgres:latest
    networks:
      - internal
    shm_size: 128mb
    hostname: postgres-invoices-dev
    ports:
      - 5634:5432
    volumes:
      - ./postgresql-invoices-dev:/var/lib/postgresql/
    environment:
      POSTGRES_DB: invoices_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.useBindPortIP=true"
      - "--providers.docker.network=internal"
      - "--entrypoints.web.address=:80"
    networks:
      - internal
    ports:
      - "80:80"
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  internal:
    name: internal
    driver: bridge

