services:
  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.useBindPortIP=true"
      - "--providers.docker.network=development"
      - "--entrypoints.web.address=:80"
    networks:
      - development
      - testing
      - production
    ports:
      - "80:80"
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  development:
    driver: bridge
  testing:
    driver: bridge
  production:
    driver: bridge